### ISSUE TITLE
Release v1.0.1

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#118]
### Release Version V1.0.1

- [x] Create release branch for v1.0.1
- [x] Use latest master as candidate V1.0.1 of Atlas and deploy to development
- [x] Generate Atlas Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish Release
- [x] Update Jenkins automation to point to "released" branch to obtain latest stable build for OHDSI.org
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
