### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#127]
### Release Version V1.1.0

- [x] Deploy Atlas + new result schema changes for cohort inclusion tables
- [x] Generate Atlas Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
