### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#203]
### Release Version V1.2.0

- [x] Create release branch for v1.2.0
- [x] Use latest master as candidate V1.2.0 of Atlas and deploy to development
- [x] Generate Atlas Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish Release
- [x] Update Jenkins automation to point to "released" branch to obtain latest stable build for OHDSI.org
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
