### ISSUE TITLE
Release v1.3.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#243]
### Release Version V1.3.0

- [x] Use latest master as candidate V1.3.0 of Atlas and deploy to development
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Communicate production change to team
- [x] Create release branch for v1.3.0
- [x] Generate Atlas Release Notes
- [x] Publish Release
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
