### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#359]
### Release Version V2.0.0
- [x] Create merge branch for v2.0.0. Deploy to development for testing
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Communicate production change to team
- [x] Generate Atlas Release Notes
- [x] Publish Release
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums

New Features
	- Fully dynamic data sources expose Achilles data via WebAPI. Thanks to @t-abdul-basser and @mark-velez for this implementation
	- #86 - Initial security implementation. See the OHDSI wiki for more information: http://www.ohdsi.org/web/wiki/doku.php?id=development:security
	- #212, #225, #229, #231 - Enhancements to vocabulary search and results
	- #20, #187, #204, #305 - Enhancements to estimation including R-code generated utilizes the Multi-analysis approach detailed in Cohort Method package repository.
	- #176, #177, #188, #303 - Patient profile enhancements
	- #52, #307, #309, #313 - System level refactoring around state and route management and refactoring of REST endpoint calls to match new approach in WebAPI 2.0

Fixes
	- #32 - Table heading alignment
	- #101 - Recent search links
	- #102 - Last modified on cohort search
	- #103 - Clear filter on new vocab search
	- #165 - Select all concept button broken
	- #181 - Data source error when data source name contains spaces
	- #218 - Problem search box vocabulary
	- #223 - Cartoon not rendering, navigation bug
	- #234 - Patient profiles no longer linkable
	- #248 - Estimation navigation error
	- #261 - Cohort references in estimation
	- #263 - Estimation concept set resolution
	- #319 - Export multiple concept sets
	- #320 - Changing data sources without selecting a report
	- #329 - Observation period as initial event
	- #330 - Bug in explore tab
	- #331 - Vocab search - no more results tab and breadcrumbs
	- #333 - Concept set comparison
	- #336 - Configure vocabulary does not switch source that is queried
	- #338 - initialization error
	- #341 - Redundant WebAPI calls
	- #342 - App startup errors
	- #344 - Concept set optimization bug
	- #355 - Search results view missing heading

Important Notes
	- V2.0.0 of Atlas now depends on V2.0.0 of WebAPI since REST end-point routes have changed.
