### ISSUE TITLE
V1.0.0 Release Steps

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#45]
### Release Version V1.0.0

- [x] Use latest master as candidate V1.1.0 of WebAPI and deploy to development
- [x] Generate Atlas Release Notes
- [x] Generate WebAPI Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Tag Atlas as V1.0.0
- [x] Tag WebAPI as V1.1.0
- [x] Update Jenkins automation to point to "released" branch to obtain latest stable build for OHDSI.org
- [x] Merge charon branch into master & remove
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
