### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#480]
### Release Version V2.2.0
- [ ] Create merge branch for v2.2.0. Deploy to development for testing
- [ ] Update [setup documentation](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:setup)
- [ ] Complete user acceptance testing
- [ ] Obtain sign off
- [ ] Communicate production change to team
- [ ] Generate Atlas Release Notes
- [ ] Publish Release
- [ ] Update OHDSI.org
- [ ] Communicate release via OHDSI forums

Please see [V2.2.0](https://github.com/OHDSI/Atlas/releases/tag/untagged-381862199247eefe4cd3) for the release notes

**Comment by jmbanda** [comment]
Great job on the new release! Everything seems to be working in order except for a few issues with the plots in the Sources section. It happens for the condition, conditionera, procedure, drug, drugera, measurement, observation. See the attached console error. 
![atlas_era](https://user-images.githubusercontent.com/10423944/31469494-a2987044-ae96-11e7-89c6-29766c17c07a.PNG)

Going into the actual url for the webapi call it shows that there is something funky going on when constructing the query with the vocabulary:

``
"ERROR","schema":null,"sqlstate":"42P01","message":"relation \"rs_schema_stride7_strict.concept_hierarchy\" does not exist","file":"parse_relation.c","table":null},"sqlstate":"42P01","nextException":null,"errorCode":0,"message":"ERROR: relation \"rs_schema_stride7_strict.concept_hierarchy\" does not exist\n  Position: 835","localizedMessage":"ERROR: relation \"rs_schema_stride7_strict.concept_hierarchy\" does not exist\n  Position: 835","suppressed":[]},"stackTrace":[{"methodName":"doTranslate","fileName":"SQLErrorCodeSQLExceptionTranslator.java","lineNumber":231,"className":"org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator","nativeMethod":false},
``

And plenty more errors like this one.

Seems to be using the Results daimon instead of the Vocabulary daimon to build these queries (it is the same for all other ones I mentioned). So this is probably a Web API 2.2.0 error. 

Just as info: I am using both WebAPI 2.2.0 and Atlas 2.2.0. Let me know if you have any questions that might help resolve this issue.

**Comment by chrisknoll** [comment]
@jmbanda , we're going to re-publish 2.2.0 in a few hours with some fixes.  
For the specific problem you are having with the 'concept_hierarchy' table, there's a new command available in Achilles 1.5 which creates these tables. this command must be executed if you are going to use WebAPI 2.2.0.  Stand by for an update to this release!

**Comment by anthonysena** [comment]
@jmbanda - thanks for this note! As @chrisknoll mentioned, there are some new Achilles commands in v1.5.0 that need to be run if you have an existing CDM with Achilles results. We've created a wiki article which describes the changes and how to add the new Achilles dependencies required by WebAPI/Atlas:

[Achilles v1.5.0 Dependencies For WebAPI/Atlas](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:achilles_v_1_5)

Please let us know if there is anything unclear in the article or if you face any problems as you get V2.2 set up in your environment.

**Comment by jmbanda** [comment]
Thanks for all the help! @anthonysena  @chrisknoll I have followed the instructions and got the new tables generated. However, I now get the following error in all the plots with Treemaps (including visit).
![new issue](https://user-images.githubusercontent.com/10423944/31510298-22fd7ab6-af39-11e7-93fb-046435fc61d9.PNG)

I have followed all instructions to build the new visualization stuff as well.  I also got the latest Atlas and purged all my browser's cache. 

Thanks!

**Comment by chrisknoll** [comment]
Did you also re-install the WebAPI v2.2.0?  The error when it can't read the propery 'map' of undefined indicates that you might not be running the latest version.  If you could inspect the 'data' object returned from the call in line 491, you should see fields like 'conceptPath' (note, the postgresql fix was a casing issue, where you might see a property called 'conceptpath'.) If you are seeing the wrong case, you should re-pull the 2.2.0 release of WebAPI and deploy it. I confirm that we are working on Postgresql based on the ohdsi.org deployment here: http://www.ohdsi.org/web/atlas/#/datasources.  You should be able to see the condition treemap report there.

**Comment by jmbanda** [comment]
Thanks! @chrisknoll Seems like when I did the pull I didn't get the latest version. All seems to be working now!
